# Site settings
title: GigaElk
email: gigaelk@gmail.com
url: https://gigaelk.com
description: "Indie software & games studio based in Tokyo"
keywords: "GigaElk, Software, Apps, Games, AR, VR, switch-n-shakes, this-way-up"
skills: "Indie Software & Games from Tokyo"
meta_author: Hewitt Andrew

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: c71c81 #80B3FF
  primary-rgb: "199,28,129" #"128,179,255"
  secondary: 3d0659 #FD6E8A
  secondary-dark: 3d0659 #A2122F

# Footer settings
footer:
  copyright: GigaElk Software
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: itch-io,
    url: https://itch.io/profile/gigaelk
  - title: twitter
    url: http://twitter.com/gigaelk
  - title: instagram
    url: https://www.instagram.com/gigaelk/
  - title: stack-overflow
    url: https://stackoverflow.com/users/1716792/gigaelk
  - title: github
    url: https://github.com/GigaElk

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Credits content
credits: 

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
